window.GRAMMAR_RULES = [
  {
    "id": "harmony",
    "title": "1. Гармония гласных (Ünlü Uyumu)",
    "subtitle": "Фундамент турецкого языка: твёрдые и мягкие гласные",
    "badge": "Основа основ",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        В турецком языке (как и в узбекском) все гласные делятся на две строгие группы — <b>твёрдые</b> (заднеязычные) и <b>мягкие</b> (переднеязычные). Аффиксы всегда подстраиваются под <b>последнюю гласную букву</b> основы слова:\n      </p>\n\n      <div class=\"grid grid-cols-1 sm:grid-cols-2 gap-2.5 mb-3 text-xs\">\n        <div class=\"p-3 rounded-xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-900/60\">\n          <div class=\"font-bold text-amber-800 dark:text-amber-300 text-sm mb-1\">Твёрдые (Kalın): A, I, O, U</div>\n          <p class=\"text-tgHint mb-2\">Произносятся глубоко в горле (как в узбекских словах: <i>qalin, ota, qiz</i>)</p>\n          <div class=\"bg-white/80 dark:bg-slate-900/80 p-2 rounded-lg font-mono text-[11px] space-y-1\">\n            <div>kapı ➔ kapı<b>lar</b> (двери)</div>\n            <div>tornavida ➔ tornavida<b>da</b> (в отвертке)</div>\n          </div>\n        </div>\n\n        <div class=\"p-3 rounded-xl bg-sky-50 dark:bg-sky-950/40 border border-sky-200 dark:border-sky-900/60\">\n          <div class=\"font-bold text-sky-800 dark:text-sky-300 text-sm mb-1\">Мягкие (İnce): E, İ, Ö, Ü</div>\n          <p class=\"text-tgHint mb-2\">Произносятся мягко у зубов (как в узбекских: <i>eshik, kel, ko'z</i>)</p>\n          <div class=\"bg-white/80 dark:bg-slate-900/80 p-2 rounded-lg font-mono text-[11px] space-y-1\">\n            <div>menteşe ➔ menteşe<b>ler</b> (петли)</div>\n            <div>profil ➔ profil<b>de</b> (в профиле)</div>\n          </div>\n        </div>\n      </div>\n\n      <div class=\"p-3 rounded-xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-900 text-xs space-y-1.5\">\n        <div class=\"font-bold text-emerald-800 dark:text-emerald-300 flex items-center gap-1.5\">\n          <span>🇺🇿</span>\n          <span>Сравнение с узбекским:</span>\n        </div>\n        <p class=\"text-tgText/90\">\n          В узбекском языке множественное число всегда <b>-lar</b> (<i>eshiklar, qizlar</i>). В турецком же оно подчиняется гармонии на 2 варианта: <b>-lar</b> (после твёрдых) или <b>-ler</b> (после мягких).\n        </p>\n      </div>\n    "
  },
  {
    "id": "plurals",
    "title": "2. Множественное число (-lar / -ler)",
    "subtitle": "Как делать предметы множественными",
    "badge": "Множественное число",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        Аффикс множественного числа добавляется в самый конец основы слова:\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">civata ➔ civata<b>lar</b></span>\n            <span class=\"text-tgHint ml-2\">(болт ➔ болты)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 boltlar</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">ölçü ➔ ölçü<b>ler</b></span>\n            <span class=\"text-tgHint ml-2\">(размер ➔ размеры)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 o'lchamlar</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">fitil ➔ fitil<b>ler</b></span>\n            <span class=\"text-tgHint ml-2\">(уплотнитель ➔ уплотнители)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 rezina qistirmalar</span>\n        </div>\n      </div>\n\n      <div class=\"p-3 rounded-xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-900 text-xs\">\n        <b class=\"text-amber-800 dark:text-amber-300\">Важное цеховое правило:</b> \n        Если перед словом стоит число или количество, окончание <b>-lar/-ler НЕ ставится</b>!\n        <div class=\"mt-1 font-mono text-[11px] text-tgText\">\n          İki profil (два профиля, а НЕ <s>iki profiller</s>). Точно так же, как в узбекском: <i>ikkita profil</i>!\n        </div>\n      </div>\n    "
  },
  {
    "id": "cases",
    "title": "3. Цеховые падежи и предлоги",
    "subtitle": "Где лежит, куда положить, откуда взять",
    "badge": "Падежи",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        В турецком языке нет предлогов «в, на, из, к» — вместо них к концу слова прикрепляются падежные аффиксы:\n      </p>\n\n      <div class=\"space-y-2.5 mb-3 text-xs\">\n        <!-- Местный -->\n        <div class=\"p-3 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 space-y-1\">\n          <div class=\"flex items-center justify-between\">\n            <span class=\"font-bold text-sky-600 dark:text-sky-400 text-sm\">Где? (Местный): -da / -de / -ta / -te</span>\n            <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 -da</span>\n          </div>\n          <div class=\"text-tgText/90\">masada (на столе), atölyede (в цеху), rafta (на полке)</div>\n        </div>\n\n        <!-- Направительный -->\n        <div class=\"p-3 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 space-y-1\">\n          <div class=\"flex items-center justify-between\">\n            <span class=\"font-bold text-sky-600 dark:text-sky-400 text-sm\">Куда? (Дательный): -a / -e / -ya / -ye</span>\n            <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 -ga / -ka</span>\n          </div>\n          <div class=\"text-tgText/90\">depoya (на склад), makineye (к станку), içeriye (внутрь)</div>\n        </div>\n\n        <!-- Исходный -->\n        <div class=\"p-3 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 space-y-1\">\n          <div class=\"flex items-center justify-between\">\n            <span class=\"font-bold text-sky-600 dark:text-sky-400 text-sm\">Откуда? (Исходный): -dan / -den / -tan / -ten</span>\n            <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 -dan</span>\n          </div>\n          <div class=\"text-tgText/90\">kutudan (из коробки), depodan (со склада), fabrikadan (с завода)</div>\n        </div>\n\n        <!-- Винительный -->\n        <div class=\"p-3 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 space-y-1\">\n          <div class=\"flex items-center justify-between\">\n            <span class=\"font-bold text-sky-600 dark:text-sky-400 text-sm\">Кого? Что? (Винительный): -ı / -i / -u / -ü</span>\n            <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 -ni</span>\n          </div>\n          <div class=\"text-tgText/90\">Profili kes (Отрежь профиль! / <i>Profilni kes</i>), vidayı sık (Затяни винт! / <i>Vintni qotir</i>)</div>\n        </div>\n      </div>\n    "
  },
  {
    "id": "imperative",
    "title": "4. Повелительное наклонение и команды в цеху",
    "subtitle": "«Сделай», «Отрежь», «Не трогай», «Проверьте»",
    "badge": "Команды",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        Чтобы дать команду коллеге или напарнику, берется чистый корень глагола (без окончания инфинитива -mak / -mek):\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Kes!</span>\n            <span class=\"text-tgText/90 ml-2\">Режь! Отрезай!</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Kes!</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Getir!</span>\n            <span class=\"text-tgText/90 ml-2\">Принеси! Дай сюда!</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Keltir! / Olib kel!</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Bırak!</span>\n            <span class=\"text-tgText/90 ml-2\">Оставь! Отпусти!</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Qoldir! / Qo'yib yubor!</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Dokunma!</span>\n            <span class=\"text-tgText/90 ml-2\">Не трогай! (Опасно)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Tegma!</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Bakın! / Kontrol edin!</span>\n            <span class=\"text-tgText/90 ml-2\">Посмотрите! / Проверьте! (вежливо на «Вы»)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Qarang! / Tekshiring!</span>\n        </div>\n      </div>\n\n      <div class=\"p-3 rounded-xl bg-sky-50 dark:bg-sky-950/40 border border-sky-200 dark:border-sky-900 text-xs\">\n        <b>Вежливая форма на «Вы»:</b> добавьте к корню <b>-in / -ın / -ün / -un</b>.  \n        Например: <i>Gel</i> (иди) ➔ <i>Gelin</i> (проходите / <i>keling</i>), <i>Dur</i> (стой) ➔ <i>Durun</i> (стойте / <i>to'xtang</i>).\n      </div>\n    "
  },
  {
    "id": "word_order",
    "title": "5. Порядок слов в предложении (SOV)",
    "subtitle": "Подлежащее ➔ Дополнение ➔ Глагол (всегда в конце)",
    "badge": "Структура речи",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        В турецком языке сказуемое/действие <b>ВСЕГДА стоит в самом конце фразы</b>. Это полностью идентично узбекскому языку:\n      </p>\n\n      <div class=\"p-3 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 space-y-2 mb-3 text-xs\">\n        <div class=\"font-mono text-sm text-sky-600 dark:text-sky-400\">\n          Ben [кто] + profili [что] + kestim [сделал].\n        </div>\n        <div class=\"text-tgText/90\">Я профиль отрезал.</div>\n        <div class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Men profilni kesdim.</div>\n      </div>\n\n      <div class=\"p-3 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 space-y-2 mb-3 text-xs\">\n        <div class=\"font-mono text-sm text-sky-600 dark:text-sky-400\">\n          Usta [кто] + contayı [что] + takıyor [делает].\n        </div>\n        <div class=\"text-tgText/90\">Мастер уплотнитель устанавливает.</div>\n        <div class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Usta rezina qistirmasini taqyapti.</div>\n      </div>\n\n      <p class=\"text-xs text-tgHint leading-relaxed\">\n        💡 <i>Вопрос:</i> В самый конец перед вопросительным знаком ставится частица <b>mı / mi / mu / mü</b> (аналог узбекской <i>-mi</i>):  \n        <i>Bitti mi?</i> = Закончил ли? (узб. <i>Bitdimi? / Tugadimi?</i>).\n      </p>\n    "
  },
  {
    "id": "present_continuous",
    "title": "6. Настоящее время (-iyor / процесс сейчас)",
    "subtitle": "Что происходит прямо в этот момент в цеху",
    "badge": "Настоящее время",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        Когда действие происходит прямо сейчас, к корню глагола добавляется суффикс <b>-(i)yor</b> + личное окончание (аналог узбекского <b>-yapti / -yapman</b>):\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Ne yapıyorsun?</span>\n            <span class=\"text-tgText/90 ml-2\">Что ты делаешь (сейчас)?</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Nima qilyapsan?</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Çalışıyorum.</span>\n            <span class=\"text-tgText/90 ml-2\">Я работаю.</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Ishlayapman.</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Makine çalışmıyor.</span>\n            <span class=\"text-tgText/90 ml-2\">Станок не работает / сломан.</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Dastgoh ishlamayapti.</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Geliyorum.</span>\n            <span class=\"text-tgText/90 ml-2\">Я иду / подхожу.</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Kelyapman.</span>\n        </div>\n      </div>\n    "
  },
  {
    "id": "possession",
    "title": "7. Притяжательные аффиксы («Мой», «Твой», «Его»)",
    "subtitle": "«Мой станок», «твой чертёж», «размер рамы»",
    "badge": "Притяжание",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        В турецком языке принадлежность выражается суффиксом на самом существительном (точно так же, как в узбекском):\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">projem / işim</span>\n            <span class=\"text-tgText/90 ml-2\">мой проект / моя работа</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 loyiham / ishim</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">projen / işin</span>\n            <span class=\"text-tgText/90 ml-2\">твой проект / твоя работа</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 loyihang / ishing</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">kasa profili</span>\n            <span class=\"text-tgText/90 ml-2\">профиль рамы (Schüco изафет)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 rama profili</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">cam çıtası</span>\n            <span class=\"text-tgHint ml-2\">штапик стекла</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 oyna shtapigi</span>\n        </div>\n      </div>\n    "
  },
  {
    "id": "var_yok",
    "title": "8. «Есть» и «Нет» (Var / Yok)",
    "subtitle": "Наличие инструмента, деталей или брака",
    "badge": "Наличие",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        Слова <b>Var</b> (есть, имеется) и <b>Yok</b> (нет, отсутствует) — самые частые слова на производстве. Они полностью соответствуют узбекским <b>Bor</b> и <b>Yo'q</b>:\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Çizik var mı?</span>\n            <span class=\"text-tgText/90 ml-2\">Царапина есть?</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Chizilgan joyi bormi?</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Problem yok.</span>\n            <span class=\"text-tgText/90 ml-2\">Проблем нет, всё в порядке.</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Muammo yo'q.</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Zaman yok, acele et!</span>\n            <span class=\"text-tgText/90 ml-2\">Времени нет, поторопись!</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Vaqt yo'q, shoshil!</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Depoda vida var mı?</span>\n            <span class=\"text-tgText/90 ml-2\">На складе есть винты?</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Omborda vint bormi?</span>\n        </div>\n      </div>\n    "
  },
  {
    "id": "past_tense",
    "title": "9. Прошедшее время (-di / -dı)",
    "subtitle": "Действие уже завершено (я сделал, мы закончили)",
    "badge": "Прошедшее",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        Прошедшее категорическое время образуется с помощью аффикса <b>-di / -dı / -du / -dü</b> (или <b>-ti / -tı / -tu / -tü</b> после глухих согласных). К нему добавляется личный аффикс:\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Yaptım.</span>\n            <span class=\"text-tgText/90 ml-2\">Я сделал.</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Qildim.</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Bitirdik.</span>\n            <span class=\"text-tgText/90 ml-2\">Мы закончили.</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Tugatdik.</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Makine bozuldu.</span>\n            <span class=\"text-tgText/90 ml-2\">Станок сломался.</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Dastgoh buzildi.</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Gelmedin.</span>\n            <span class=\"text-tgText/90 ml-2\">Ты не пришел (отрицание -me + -di).</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Kelmading.</span>\n        </div>\n      </div>\n      \n      <div class=\"p-3 rounded-xl bg-sky-50 dark:bg-sky-950/40 border border-sky-200 dark:border-sky-900 text-xs mt-3\">\n        <b>Важное правило (Fıstıkçı Şahap):</b> Если глагол заканчивается на глухую согласную (f, s, t, k, ç, ş, h, p), то <b>d</b> превращается в <b>t</b>. \n        <br>Пример: <i>Kes</i> (Режь) -> <i>Kesti</i> (Он отрезал). <i>Yap</i> (Делай) -> <i>Yaptı</i> (Он сделал).\n      </div>\n    "
  },
  {
    "id": "future_tense",
    "title": "10. Будущее время (-ecek / -acak)",
    "subtitle": "Планы и намерения (я сделаю, мы пойдем)",
    "badge": "Будущее",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        Будущее время образуется с помощью аффиксов <b>-ecek / -acak</b> в зависимости от гармонии гласных:\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Yapacağım.</span>\n            <span class=\"text-tgText/90 ml-2\">Я сделаю (k меняется на ğ).</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Qilaman.</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Geleceğiz.</span>\n            <span class=\"text-tgText/90 ml-2\">Мы придем (k меняется на ğ).</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Kelamiz.</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Ne zaman bitecek?</span>\n            <span class=\"text-tgText/90 ml-2\">Когда (это) закончится?</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Qachon tugaydi?</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Olmayacak.</span>\n            <span class=\"text-tgText/90 ml-2\">Этого не будет / не получится (отрицание).</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Bo'lmaydi.</span>\n        </div>\n      </div>\n      \n      <div class=\"p-3 rounded-xl bg-sky-50 dark:bg-sky-950/40 border border-sky-200 dark:border-sky-900 text-xs mt-3\">\n        <b>Обратите внимание:</b> В первом лице (Я и Мы) согласная <b>k</b> на конце аффикса смягчается и превращается в нечитаемую <b>ğ</b> (Yapacam / Yapacaz в разговорной речи).\n      </div>\n    "
  },
  {
    "id": "aorist_tense",
    "title": "11. Широкое время (Aorist: -ar / -er / -r)",
    "subtitle": "Регулярные действия, вежливые просьбы, обещания",
    "badge": "Вежливость",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        Широкое время (Geniş Zaman) используется для действий, которые происходят \"вообще, всегда\", а также для <b>очень вежливых просьб</b> на производстве:\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Yaparım.</span>\n            <span class=\"text-tgText/90 ml-2\">Сделаю (конечно, без проблем).</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Qilaman (albatta).</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Bakar mısın?</span>\n            <span class=\"text-tgText/90 ml-2\">Ты не мог бы посмотреть? (Вежливая просьба)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Qarab yuborasanmi?</span>\n        </div>\n        \n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Yardım eder misin?</span>\n            <span class=\"text-tgText/90 ml-2\">Поможешь? (Вежливо)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Yordam berasanmi?</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Olmaz!</span>\n            <span class=\"text-tgText/90 ml-2\">Нельзя! / Невозможно! (Отрицание).</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Bo'lmaydi / Mumkin emas!</span>\n        </div>\n      </div>\n      \n      <div class=\"p-3 rounded-xl bg-sky-50 dark:bg-sky-950/40 border border-sky-200 dark:border-sky-900 text-xs mt-3\">\n        В турецком языке <b>olmaz</b> (отрицание от olur - \"бывает/можно\") — это самое популярное слово для категоричного отказа на стройке и заводе.\n      </div>\n    "
  },
  {
    "id": "must_should",
    "title": "12. Долженствование (-malı / -meli / lazım)",
    "subtitle": "Нужно сделать, необходимо, обязан",
    "badge": "Обязанность",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        Чтобы сказать \"нужно\" или \"должен\", в турецком используется слово <b>lazım</b> (надо) или аффиксы <b>-malı / -meli</b>:\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Yapmam lazım.</span>\n            <span class=\"text-tgText/90 ml-2\">Мне нужно (это) сделать.</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Qilishim kerak.</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Kesmemiz lazım.</span>\n            <span class=\"text-tgText/90 ml-2\">Нам нужно отрезать.</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Kesishimiz kerak.</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Kontrol etmeliyiz.</span>\n            <span class=\"text-tgText/90 ml-2\">Мы обязаны проверить.</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Tekshirishimiz shart.</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Dikkatli olmalısın!</span>\n            <span class=\"text-tgText/90 ml-2\">Ты должен быть осторожным!</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Ehtiyot bo'lishing kerak!</span>\n        </div>\n      </div>\n    "
  },
  {
    "id": "question_particles",
    "title": "13. Вопросительные частицы (mı / mi / mu / mü)",
    "subtitle": "Как задать вопрос со смыслом «Да/Нет»",
    "badge": "Вопросы",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        В турецком языке нет интонационных вопросов (как в русском). Чтобы задать вопрос, на который можно ответить Да или Нет, используется частица <b>mı / mi / mu / mü</b>. Она пишется <b>раздельно</b> и подчиняется гармонии гласных:\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Hazır mı?</span>\n            <span class=\"text-tgText/90 ml-2\">Готово?</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Tayyormi?</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Bitti mi?</span>\n            <span class=\"text-tgText/90 ml-2\">Закончилось? / Сделал?</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Tugadimi?</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Doğru mu?</span>\n            <span class=\"text-tgText/90 ml-2\">Правильно? / Верно?</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 To'g'rimi?</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Gördün mü?</span>\n            <span class=\"text-tgText/90 ml-2\">Ты видел?</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Ko'rdingmi?</span>\n        </div>\n      </div>\n    "
  },
  {
    "id": "demonstrative_pronouns",
    "title": "14. Указательные местоимения (Bu / Şu / O)",
    "subtitle": "Это, То, Вон То",
    "badge": "Указание",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        На производстве очень часто нужно просто указать пальцем на деталь. Для этого используются три слова в зависимости от дистанции:\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800\">\n          <div class=\"flex items-center justify-between mb-1\">\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Bu (Это)</span>\n            <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Bu</span>\n          </div>\n          <div class=\"text-tgText/90\">Предмет прямо у вас в руках или совсем рядом. <br><i>Пример: Bunu al (Возьми это).</i></div>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800\">\n          <div class=\"flex items-center justify-between mb-1\">\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Şu (То)</span>\n            <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Shu</span>\n          </div>\n          <div class=\"text-tgText/90\">Предмет чуть дальше, нужно дотянуться или указать пальцем. <br><i>Пример: Şunu getir (Принеси то).</i></div>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800\">\n          <div class=\"flex items-center justify-between mb-1\">\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">O (Вон то / Он)</span>\n            <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 U</span>\n          </div>\n          <div class=\"text-tgText/90\">Предмет далеко от вас обоих, или речь о третьем лице. <br><i>Пример: O nerede? (Где он/оно?).</i></div>\n        </div>\n      </div>\n      \n      <div class=\"p-3 rounded-xl bg-sky-50 dark:bg-sky-950/40 border border-sky-200 dark:border-sky-900 text-xs mt-3\">\n        <b>Также для мест:</b> Buraya (Сюда), Şuraya (Вон туда), Oraya (Туда далеко).<br>\n        <i>Buraya koy (Положи сюда).</i>\n      </div>\n    "
  },
  {
    "id": "comparisons",
    "title": "15. Сравнения (Daha / En)",
    "subtitle": "Больше, меньше, самый лучший",
    "badge": "Сравнения",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        Чтобы сравнивать профили, размеры или качество, вам понадобятся два слова: <b>Daha</b> (Более / Еще) и <b>En</b> (Самый).\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Daha büyük</span>\n            <span class=\"text-tgText/90 ml-2\">Побольше (более большой)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Kattaroq</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Daha kısa</span>\n            <span class=\"text-tgText/90 ml-2\">Покороче (более короткий)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Qisqaroq</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Biraz daha</span>\n            <span class=\"text-tgText/90 ml-2\">Еще чуть-чуть (когда двигаете деталь)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Yana ozgina</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">En iyi</span>\n            <span class=\"text-tgText/90 ml-2\">Самый лучший</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Eng yaxshi</span>\n        </div>\n      </div>\n    "
  },
  {
    "id": "spatial_postpositions",
    "title": "16. Где находится? (İçinde / Üstünde)",
    "subtitle": "Внутри, сверху, снизу, сзади",
    "badge": "Пространство",
    "html": "\n      <p class=\"text-sm text-tgText/90 leading-relaxed mb-3\">\n        В отличие от русского, где мы используем предлоги (\"в\", \"на\"), в турецком используются <b>послелоги</b> с притяжательным аффиксом. Это очень нужно при поиске деталей и инструментов на складе.\n      </p>\n\n      <div class=\"space-y-2 mb-3 text-xs\">\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Kutunun içinde</span>\n            <span class=\"text-tgText/90 ml-2\">В коробке (букв. коробки в-ее-нутре)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Quti ichida</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Masanın üstünde</span>\n            <span class=\"text-tgText/90 ml-2\">На столе (стола на-его-верху)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Stol ustida</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Makinenin arkasında</span>\n            <span class=\"text-tgText/90 ml-2\">За станком (позади станка)</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Dastgoh orqasida</span>\n        </div>\n\n        <div class=\"p-2.5 rounded-xl bg-tgSecBg border border-slate-200 dark:border-slate-800 flex items-center justify-between\">\n          <div>\n            <span class=\"font-bold text-sky-600 dark:text-sky-400\">Profilin altında</span>\n            <span class=\"text-tgText/90 ml-2\">Под профилем</span>\n          </div>\n          <span class=\"text-emerald-600 dark:text-emerald-400 font-medium\">🇺🇿 Profil ostida</span>\n        </div>\n      </div>\n    "
  }
];
